# Generated by Django 4.0 on 2021-12-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dajax', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dajax_model',
            new_name='DajaxModel',
        ),
    ]
